### ISSUE TITLE
how to add the styles to ul and li and how to style the button wich is generated by the FakeSelect ?

### ISSUE THREAD

**Issue by adnanmayo** [takien/FakeSelect#2]

**Comment by takien** [comment]
you can pass via config.

    $('.fake-select').fakeSelect({
	  btnSize :'btn-sm', //btn-lg etc
	  btnStyle:'btn-danger' // bootstrap button style
    });`

or if you want to style yourself, use CSS.
all element generated by FakeSelect wrapped by `.fake-select-wrap` class.

so you can do this
    .fake-select-wrap .dropdown-menu  {
        /* your style here */
    }

**Comment by adnanmayo** [comment]
@takien  thanks you saved my life
